"""add sentiment columns to notes

Revision ID: 3775fb4bb086
Revises: 619df978e674
Create Date: 2025-08-27 20:27:40.172417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3775fb4bb086'
down_revision: Union[str, Sequence[str], None] = '619df978e674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('note_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('jobs_note_it_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'notes', ['note_id'], ['id'], ondelete='CASCADE')
    op.drop_column('jobs', 'note_it')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('note_it', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_note_it_fkey'), 'jobs', 'notes', ['note_it'], ['id'], ondelete='CASCADE')
    op.drop_column('jobs', 'note_id')
    # ### end Alembic commands ###
