"""make jobs.detail nullable

Revision ID: 57011f646638
Revises: 3775fb4bb086
Create Date: 2025-08-27 20:36:39.868820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57011f646638'
down_revision: Union[str, Sequence[str], None] = '3775fb4bb086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'detail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'detail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
