"""add sentiment columns to notes

Revision ID: ad65eca9e3c8
Revises: 297e4221721d
Create Date: 2025-08-27 19:10:45.931624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad65eca9e3c8'
down_revision: Union[str, Sequence[str], None] = '297e4221721d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('sentiment', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('sentiment_model', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('analyzed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'analyzed_at')
    op.drop_column('notes', 'sentiment_model')
    op.drop_column('notes', 'sentiment')
    # ### end Alembic commands ###
